export const MAKE_REQUEST = "MAKE_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const PUT_DATA_SUCCESS = "PUT_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";